'''Utility functions and variables for the project'''

IGNORED_PARAGRAPHS = [
    'skip to main content',
    'job i dag',
    'jobsøgning',
    'din indbakke',
    'opret dit cv',
    'søg job',
    'jobagent',
    'næste arbejdsplads',
    'jobsamtale',
    'send me alerts',
    'start applying with linkedin',
    'please contact your manager',
    'press tab to ',
    'job req number',
    'terms and conditions',
    'existing user',
    'apply',
    'enter a',
    'copyright',
    'cookie',
    'up and down arrows',
    'please enter',
    'please select',
    'current mailing address',
    'privacy information',
    'regulation (eu)',
    'policy',
    'type of data processed',
    'personal data',
    'purpose and legal basis',
    'data controller',
    'gdpr',
    'rights',
    'more information',
    'du kan søge',
    'application',
    'cover letter',
    'read more',
    'questions about the position',
    'join our talent community',
    'keyword',
    'alerts',
    'browser',
]
